In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
df = pd.read_csv('CarPrice_assignment.csv')
min_max_scaler = preprocessing.MinMaxScaler()

In [3]:
df.head(100)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,1,nissan juke,gas,std,two,hatchback,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799.0
96,97,1,nissan latio,gas,std,four,sedan,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499.0
97,98,1,nissan note,gas,std,four,wagon,fwd,front,94.5,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999.0
98,99,2,nissan clipper,gas,std,two,hardtop,fwd,front,95.1,...,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249.0
99,100,0,nissan rogue,gas,std,four,hatchback,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949.0

In [4]:
df=df.replace(to_replace='4wd',value='fwd')

In [5]:
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,fwd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

In [6]:
X = df.drop(['price','car_ID','CarName'],1)
Y = df.price

In [7]:
X

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,four,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,six,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,four,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,2,gas,std,four,sedan,fwd,front,99.4,176.6,66.4,...,five,136,mpfi,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,four,141,mpfi,3.78,3.15,9.5,114,5400,23,28
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,four,141,mpfi,3.78,3.15,8.7,160,5300,19,25
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,six,173,mpfi,3.58,2.87,8.8,134,5500,18,23
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,six,145,idi,3.01,3.40,23.0,106,4800,26,27
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,four,141,mpfi,3.78,3.15,9.5,114,5400,19,25

In [8]:
Y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [9]:
X.columns = X.columns.str.strip()
todummy_list = ['fuelsystem','cylindernumber','enginetype','enginelocation','drivewheel','carbody','doornumber','aspiration','fueltype']

In [10]:
def dummy_df(data,todummy_list):
        for x in todummy_list:
            dummies = pd.get_dummies(data[x], prefix=x,dummy_na=False)
            data = data.drop(x,1)
            data = pd.concat([data,dummies],axis=1)
        return data

In [11]:
X = dummy_df(X,todummy_list)
X

,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,...,carbody_hardtop,carbody_hatchback,carbody_sedan,carbody_wagon,doornumber_four,doornumber_two,aspiration_std,aspiration_turbo,fueltype_diesel,fueltype_gas
0,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,1,1,0,0,1
1,3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9.0,...,0,0,0,0,0,1,1,0,0,1
2,1,94.5,171.2,65.5,52.4,2823,152,2.68,3.47,9.0,...,0,1,0,0,0,1,1,0,0,1
3,2,99.8,176.6,66.2,54.3,2337,109,3.19,3.40,10.0,...,0,0,1,0,1,0,1,0,0,1
4,2,99.4,176.6,66.4,54.3,2824,136,3.19,3.40,8.0,...,0,0,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,3.78,3.15,9.5,...,0,0,1,0,1,0,1,0,0,1
201,-1,109.1,188.8,68.8,55.5,3049,141,3.78,3.15,8.7,...,0,0,1,0,1,0,0,1,0,1
202,-1,109.1,188.8,68.9,55.5,3012,173,3.58,2.87,8.8,...,0,0,1,0,1,0,1,0,0,1
203,-1,109.1,188.8,68.9,55.5,3217,145,3.01,3.40,23.0,...,0,0,1,0,1,0,0,1,1,0
204,-1,109.1,188.8,68.9,55.5,3062,141,3.78,3.15,9.5,...,0,0,1,0,1,0,0,1,0,1

In [12]:
x_scaled = min_max_scaler.fit_transform(X)
X = pd.DataFrame(x_scaled)
print(X)

      0         1         2         3         4         5         6   \
0    1.0  0.058309  0.413433  0.316667  0.083333  0.411171  0.260377
1    1.0  0.058309  0.413433  0.316667  0.083333  0.411171  0.260377
2    0.6  0.230321  0.449254  0.433333  0.383333  0.517843  0.343396
3    0.8  0.384840  0.529851  0.491667  0.541667  0.329325  0.181132
4    0.8  0.373178  0.529851  0.508333  0.541667  0.518231  0.283019
..   ...       ...       ...       ...       ...       ...       ...
200  0.2  0.655977  0.711940  0.716667  0.641667  0.567882  0.301887
201  0.2  0.655977  0.711940  0.708333  0.641667  0.605508  0.301887
202  0.2  0.655977  0.711940  0.716667  0.641667  0.591156  0.422642
203  0.2  0.655977  0.711940  0.716667  0.641667  0.670675  0.316981
204  0.2  0.655977  0.711940  0.716667  0.641667  0.610551  0.301887

           7         8        9   ...   41   42   43   44   45   46   47   48  \
0    0.664286  0.290476  0.12500  ...  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0
1    0.664286  0.290476  0.12500  ...  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0
2    0.100000  0.666667  0.12500  ...  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0
3    0.464286  0.633333  0.18750  ...  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
4    0.464286  0.633333  0.06250  ...  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
..        ...       ...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
200  0.885714  0.514286  0.15625  ...  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
201  0.885714  0.514286  0.10625  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
202  0.742857  0.380952  0.11250  ...  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0
203  0.335714  0.633333  1.00000  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0
204  0.885714  0.514286  0.15625  ...  0.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0

      49   50
0    0.0  1.0
1    0.0  1.0
2    0.0  1.0
3    0.0  1.0
4    0.0  1.0
..   ...  ...
200  0.0  1.0
201  0.0  1.0
202  0.0  1.0
203  1.0  0.0
204  0.0  1.0

[205 rows x 51 columns]

In [13]:
Y = pd.DataFrame(Y)

y_scaled = min_max_scaler.fit_transform(Y)
Y = pd.DataFrame(y_scaled)
print(Y)

            0
0    0.207959
1    0.282558
2    0.282558
3    0.219254
4    0.306142
..        ...
200  0.291123
201  0.345738
202  0.406311
203  0.430763
204  0.434611

[205 rows x 1 columns]

In [14]:

X_train, X_test,Y_train,Y_test= train_test_split(X, Y,test_size=0.30,random_state=1)  
Y_train = pd.DataFrame(Y_train).sort_index()
Y_test=pd.DataFrame(Y_test).sort_index()
Y_train
X_test

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
78,0.8,0.206997,0.241791,0.341667,0.250000,0.200155,0.116981,0.307143,0.552381,0.15000,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
97,0.6,0.230321,0.434328,0.291667,0.475000,0.212956,0.135849,0.435714,0.580952,0.15000,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
151,0.6,0.265306,0.262687,0.275000,0.558333,0.214119,0.116981,0.364286,0.457143,0.12500,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
44,0.6,0.230321,0.220896,0.275000,0.350000,0.149728,0.109434,0.350000,0.495238,0.16250,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
40,0.4,0.288630,0.511940,0.183333,0.525000,0.342901,0.184906,0.435714,0.719048,0.12500,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,0.4,0.288630,0.511940,0.408333,0.525000,0.316524,0.184906,0.435714,0.719048,0.12500,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
110,0.4,0.804665,0.862687,0.675000,0.908333,0.753297,0.343396,0.828571,0.690476,0.87500,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
164,0.6,0.230321,0.411940,0.308333,0.400000,0.277735,0.139623,0.464286,0.457143,0.12500,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
56,1.0,0.253644,0.416418,0.450000,0.150000,0.346005,0.033962,0.564286,0.564286,0.15000,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
176,0.2,0.460641,0.514925,0.516667,0.591667,0.359193,0.230189,0.550000,0.700000,0.10625,...,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [15]:
X_train = np.vstack((np.ones((X_train.shape[0], )), X_train.T)).T
X_test = np.vstack((np.ones((X_test.shape[0], )), X_test.T)).T
print("Shape of X_train :", X_train.shape)
print("Shape of Y_train :", Y_train.shape)
print("Shape of X_test :", X_test.shape)
print("Shape of Y_test :", Y_test.shape)

Shape of X_train : (143, 52)
Shape of Y_train : (143, 1)
Shape of X_test : (62, 52)
Shape of Y_test : (62, 1)

In [16]:
def model(X, Y, learning_rate, iteration):
    m = Y.size
    theta = np.random.rand(52, 1)
    cost_list = []
    for i in range(iteration):
        y_pred = np.dot(X, theta)
        cost = (1/(2*m))*np.sum(np.square(y_pred - np.array(Y)))
        d_theta = (1/m)*np.dot(X.T, y_pred - Y)
        theta = theta - learning_rate*d_theta
        cost_list.append(cost)
        # to print the cost for 10 times
        if(i%200 == 0):
#             print(Y)
#             print(y_pred)
            print( cost)
        learning_rate = learning_rate-0.000001
    return theta, cost_list

In [17]:
iterations = 10000
learning_rate = 0.01
theta, cost_list = model(X_train, Y_train, learning_rate = learning_rate, iteration = iterations)

24.997616344903403
0.19027144241936014
0.11228215783557653
0.08091209541346539
0.06458139106354843
0.05470340903560791
0.04810601322110606
0.04338723519380323
0.039843205037355715
0.03708454115269576
0.03487854351688213
0.03307719410016257
0.031581479676951955
0.03032242834383219
0.029250394377202903
0.028328673229879517
0.027529519049334324
0.026831562351250945
0.026218079578524445
0.02567580065865337
0.025194067420692818
0.024764227252312414
0.0243791883060696
0.024033087994739383
0.02372104241005309
0.023438954499950298
0.02318336554096961
0.022951338937388297
0.022740368450085226
0.022548305091985164
0.022373298432024864
0.022213749125848295
0.02206827027082417
0.02193565575397652
0.021814854184277897
0.021704947317069498
0.021605132117224337
0.021514705789635696
0.021433053245410786
0.021359636580418544
0.021293986227345553
0.021235693508874214
0.0211844043722663
0.02113981412769765
0.02110166304655979
0.021069732703457564
0.021043842968207126
0.02102384957287529
0.021009642194667572
0.02100114300895946

In [18]:
y_pred = np.dot(X_test, theta)
error = (1/X_test.shape[0])*np.sum(np.abs(y_pred - Y_test))

In [19]:
print("Test Error is :", error*100, "%")
print("Test Accuracy is :", (1- error)*100, "%")

Test Error is : 0    18.107725
dtype: float64 %
Test Accuracy is : 0    81.892275
dtype: float64 %